### ISSUE TITLE
Is this the "official" git repo for MIC? 

### ISSUE THREAD

**Issue by jeremiah** [jfding/mic#12]
There appears to be two somewhat overlapping git repos for mic. Which one is the one that I should pull from to get the latest stable mic? I ask because the versions appear to be different as well as the versioning scheme. 

Also, is the tool called mic or mic2? What is the difference between those two tools?

**Comment by jfding** [comment]
First of all, thanks for your attention for this project.
Currently, this git is the closest to the "official one", maybe we will host it in tizen.org infrastructures later as the official one, but this one will always be synced between them. And because there's no official group for Tizen in github.com, I can only put it under my personal group.

And for the other mic git you mentioned, I don't which one it is:) But we do have a private tree which was used in the design and initialization stage, and it will be deprecated later.

For the confusion of mic and mic2: mic is the latest tool, with totally new designed code architecture and much better code quality, and mic2, the old one, will not be developed ever. And we recommend all users to use the "mic", or even involve the development.

**Comment by jeremiah** [comment]
Thanks for the prompt reply!

And thank you for the clarifications. I'll pull from this repo for my mic work. I plan to test this against an SSL repo as well as against deb repos.
